version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/production/Dockerfile
    restart: always
    image: vianch-site-image
    container_name: 'vianch-site'
    volumes:
      - ./:/vianch-site
    ports:
      - "8080:8080"
    networks:
      - vianch-network
    environment:
      - APP_ENV=production
      - GATSBY_WEBPACK_PUBLICPATH=/

networks:
  vianch-network:
    name: vianch-site
