version: '3'
services:
  web:
    build:
      context: .
      dockerfile: .docker/develop/Dockerfile
    restart: on-failure:2
    image: vianch-site:develop
    container_name: 'vianch-develop'
    volumes:
      - ./:/vianch-site-develop
    ports:
      - "3000:3000"
    networks:
      - vianch-network
    environment:
      - APP_ENV=develop
      - GATSBY_WEBPACK_PUBLICPATH=/

networks:
  vianch-network:
    name: vianch-site-network
